services:
  - type: web
    name: laravel-backend
    env: docker
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: laravel-backend
          property: url
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: laraveldb
    databaseName: laravel
    user: laraveluser
    plan: free