services:
  - type: web
    name: laravel-backend
    env: docker
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      # NO agregues APP_KEY aquí, déjala que se genere
    healthCheckPath: /api/health
    autoDeploy: true